gpu: "3"
multi_gpu: null

model_name: model_msbrn
iters: 5

full: False

evaluate: True
resume: True

ckpt_dir: ./pretrain_weights/

arch: PointConvLightRes
last_relu: False
allow_less_points: False

# general args
batch_size: 1
pretrain: models_msbrn_0.0149.pth
num_points: 8192

DEVICE: cuda

dataset: KITTI # FlyingThings3DSubset KITTI
data_root:  /workspace/dataset

data_process:
  DEPTH_THRESHOLD: 35.
  NO_CORR: True

# miscalleneous
workers: 0








